services:
  db:
    image: postgres:16

    container_name: postgres-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./app

    container_name: flask-api

    depends_on:
      - db

    ports:
      - "5005:5005"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/employees
      SECRET_KEY: my-secret-key

volumes:
  postgres_data:
